---
name: py314-latest
channels:
  - conda-forge
dependencies:
  - python=3.14
  - geopandas
  - libpysal
  - numpy
  - scipy
  - scikit-learn
  - joblib
  - esda
  # optional
  - h3-py
  - healpy
  - s2sphere
  - rasterio
  - statsmodels
  # testing
  - geodatasets
  - mgwr
  # docs
  - pandarm
  - esda
  - ipykernel
  - myst-nb
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-autosummary-accessors
  - sphinx-copybutton
  - sphinx-immaterial
  - pip
  - pip:
    - pya5
