---
name: py314-latest
channels:
  - conda-forge
dependencies:
  - python=3.14
  - geopandas
  - libpysal
  - numpy
  - scipy
  - scikit-learn
  - joblib
  - esda
  # testing
  - geodatasets
  - mgwr
  # docs
  - pandarm
  - ipykernel
  - myst-nb
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-autosummary-accessors
  - sphinx-copybutton
  - sphinx-immaterial